version: '3'

services:
  nuxt:
    build: .
    ports:
      - 3003:3000
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    working_dir: /app
    command: npm run dev
